"use client";

import { useEffect, useState, useRef } from "react";
import { useProvider, useAccount, useConnect, useDisconnect } from "@starknet-react/core";
import { hash } from "starknet";
import {
    Activity,
    Server,
    FileCode,
    Wallet,
    Terminal,
    RefreshCw,
    CheckCircle2,
    XCircle,
    Zap,
    Play
} from "lucide-react";
import { redirect } from "next/navigation";

// Environment variables
const ENV_VARS = {
    NEXT_PUBLIC_GATE_ADAPTER_ADDRESS: process.env.NEXT_PUBLIC_GATE_ADAPTER_ADDRESS,
    NEXT_PUBLIC_PROOF_VERIFIER_ADDRESS: process.env.NEXT_PUBLIC_PROOF_VERIFIER_ADDRESS,
    NEXT_PUBLIC_POLICY_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_POLICY_REGISTRY_ADDRESS,
    NEXT_PUBLIC_STRKBTC_ADDRESS: process.env.NEXT_PUBLIC_STRKBTC_ADDRESS,
    NEXT_PUBLIC_STARKNET_RPC_URL: process.env.NEXT_PUBLIC_STARKNET_RPC_URL,
    NEXT_PUBLIC_DEV_MODE: process.env.NEXT_PUBLIC_DEV_MODE,
};

type LogEntry = {
    timestamp: string;
    type: "info" | "error" | "warn";
    message: string;
};

type ContractStatus = {
    address: string | undefined;
    classHash: string | null;
    isDeployed: boolean | null;
    loading: boolean;
};

export default function DevDashboard() {
    const { provider } = useProvider();
    const { address, status: accountStatus, connector, account } = useAccount();
    const { connectors, connect } = useConnect();
    const { disconnect } = useDisconnect();

    const [isAuthorized, setIsAuthorized] = useState<boolean | null>(null);

    // States
    const [logs, setLogs] = useState<LogEntry[]>([]);
    const [rpcStatus, setRpcStatus] = useState<"CONNECTED" | "FAILED" | "CHECKING">("CHECKING");
    const [networkInfo, setNetworkInfo] = useState<{
        chain: string;
        url: string;
        block: number;
        timestamp: number;
        chainId: string;
    } | null>(null);

    const [contractsStatus, setContractsStatus] = useState<Record<string, ContractStatus>>({
        PolicyRegistry: { address: ENV_VARS.NEXT_PUBLIC_POLICY_REGISTRY_ADDRESS, classHash: null, isDeployed: null, loading: false },
        ProofVerifier: { address: ENV_VARS.NEXT_PUBLIC_PROOF_VERIFIER_ADDRESS, classHash: null, isDeployed: null, loading: false },
        GateAdapter: { address: ENV_VARS.NEXT_PUBLIC_GATE_ADAPTER_ADDRESS, classHash: null, isDeployed: null, loading: false },
        STRKBTC: { address: ENV_VARS.NEXT_PUBLIC_STRKBTC_ADDRESS, classHash: null, isDeployed: null, loading: false },
    });

    const [contractTests, setContractTests] = useState<Record<string, { result: string | null, loading: boolean, error: string | null }>>({});
    const [txTest, setTxTest] = useState<{ loading: boolean; hash: string | null; error: string | null; status: string }>({
        loading: false,
        hash: null,
        error: null,
        status: ""
    });

    // Check authorization
    useEffect(() => {
        const checkAuth = () => {
            const isDev = process.env.NODE_ENV === "development";
            const isDevMode = ENV_VARS.NEXT_PUBLIC_DEV_MODE === "true";

            const searchParams = new URLSearchParams(window.location.search);
            const isKeyValid = searchParams.get("key") === "proofpass-dev-access";

            if (!isDev && !isDevMode && !isKeyValid) {
                redirect("/");
            } else {
                setIsAuthorized(true);
            }
        };
        checkAuth();
    }, []);

    // Intercept logs safely
    useEffect(() => {
        if (!isAuthorized) return;

        // Use a flag to completely ignore logs generated by React's cyclic warnings and extension injections
        const originalLog = console.log;
        const originalError = console.error;
        const originalWarn = console.warn;

        const handleLog = (type: "info" | "error" | "warn", args: any[]) => {
            try {
                const msg = args.map(a => typeof a === 'object' ? JSON.stringify(a) : String(a)).join(' ');
                if (msg.includes("Warning: ") || msg.includes("Fast Refresh") || msg.includes("HMR") || msg.includes("next_dev")) return; // ignore common dev noisy logs

                setLogs(prev => [...prev.slice(-49), {
                    timestamp: new Date().toISOString().split("T")[1].slice(0, 12),
                    type,
                    message: msg
                }]);
            } catch (e) {
                // ignore circular JSON errors etc
            }
        };

        console.log = (...args) => {
            handleLog('info', args);
            originalLog.apply(console, args);
        };
        console.error = (...args) => {
            handleLog('error', args);
            originalError.apply(console, args);
        };
        console.warn = (...args) => {
            handleLog('warn', args);
            originalWarn.apply(console, args);
        };

        return () => {
            console.log = originalLog;
            console.error = originalError;
            console.warn = originalWarn;
        };
    }, [isAuthorized]);

    // Initial Data Fetch
    useEffect(() => {
        if (!isAuthorized) return;
        fetchNetworkData();
        checkContracts();
    }, [isAuthorized, provider]);

    const fetchNetworkData = async () => {
        setRpcStatus("CHECKING");
        try {
            const block = await provider.getBlock("latest");
            const chainId = await provider.getChainId();

            setRpcStatus("CONNECTED");
            setNetworkInfo({
                chain: "Starknet Sepolia", // or extract from chainId if mainnet
                url: ENV_VARS.NEXT_PUBLIC_STARKNET_RPC_URL || "Default provider endpoint",
                block: block.block_number,
                timestamp: block.timestamp,
                chainId: chainId
            });
            console.log("[RPC] Block fetched successfully:", block.block_number);
        } catch (err: any) {
            setRpcStatus("FAILED");
            console.error("[RPC Error] Failed to fetch block:", err.message);
        }
    };

    const checkContracts = async () => {
        const keys = Object.keys(contractsStatus);

        for (const key of keys) {
            const address = contractsStatus[key].address;
            if (!address) continue;

            setContractsStatus(prev => ({
                ...prev,
                [key]: { ...prev[key], loading: true }
            }));

            try {
                const classHash = await provider.getClassHashAt(address);
                setContractsStatus(prev => ({
                    ...prev,
                    [key]: { address, classHash, isDeployed: true, loading: false }
                }));
                console.log(`[Contract] ${key} is deployed at ${address}`);
            } catch (err: any) {
                setContractsStatus(prev => ({
                    ...prev,
                    [key]: { address, classHash: null, isDeployed: false, loading: false }
                }));
                console.error(`[Contract Error] ${key} at ${address} - Not deployed`);
            }
        }
    };

    const testContractCall = async (name: string, contractAddress: string | undefined, entrypoint: string, calldata: any[] = []) => {
        if (!contractAddress) return;

        setContractTests(prev => ({
            ...prev, [name]: { result: null, loading: true, error: null }
        }));

        try {
            console.log(`[Contract Call] Testing ${name}.${entrypoint}()`);
            const result = await provider.callContract({
                contractAddress,
                entrypoint,
                calldata
            }, "latest");

            setContractTests(prev => ({
                ...prev, [name]: { result: JSON.stringify(result), loading: false, error: null }
            }));
            console.log(`[Contract Call] ${name}.${entrypoint}() success:`, result);
        } catch (err: any) {
            setContractTests(prev => ({
                ...prev, [name]: { result: null, loading: false, error: err.message }
            }));
            console.error(`[Contract Call Error] ${name}.${entrypoint}() failed:`, err.message);
        }
    };

    const executeVerifyAndRegister = async () => {
        if (!account) {
            alert("Please connect a wallet first");
            return;
        }

        setTxTest({ loading: true, hash: null, error: null, status: "Preparing transaction..." });
        console.log("[Tx Test] Starting verify_and_register test");

        try {
            if (!ENV_VARS.NEXT_PUBLIC_GATE_ADAPTER_ADDRESS) throw new Error("Gate Adapter address missing");

            setTxTest({ loading: true, hash: null, error: null, status: "Waiting for wallet signature..." });

            // Send transaction
            const { transaction_hash } = await account.execute({
                contractAddress: ENV_VARS.NEXT_PUBLIC_GATE_ADAPTER_ADDRESS,
                entrypoint: "verify_and_register",
                calldata: [0, 0, 0, 0] // dummy calldata array
            });

            console.log("[Tx Test] Tx sent successfully:", transaction_hash);
            setTxTest({ loading: false, hash: transaction_hash, error: null, status: "Tx submitted to wallet!" });
        } catch (err: any) {
            setTxTest({ loading: false, hash: null, error: err.message || JSON.stringify(err), status: "Error executing tx" });
            console.error("[Tx Test Error]", err.message || err);
        }
    };

    if (!isAuthorized) {
        return <div className="min-h-screen bg-zinc-950 flex items-center justify-center text-slate-400">Authenticating...</div>;
    }

    const StatusIcon = ({ isGood }: { isGood: boolean | null }) => {
        if (isGood === null) return <div className="w-4 h-4 rounded-full bg-zinc-700 animate-pulse" />;
        return isGood ? <CheckCircle2 className="w-5 h-5 text-emerald-500" /> : <XCircle className="w-5 h-5 text-red-500" />;
    };

    return (
        <div className="min-h-screen bg-zinc-950 text-slate-300 p-6 font-mono text-sm pb-24">
            <div className="max-w-7xl mx-auto space-y-6">

                {/* Header */}
                <div className="flex items-center justify-between pb-4 border-b border-zinc-800">
                    <div className="flex items-center gap-3">
                        <Zap className="w-6 h-6 text-amber-500" />
                        <h1 className="text-2xl font-bold text-white tracking-tight">ProofPass Diagnostics</h1>
                        <span className="px-2 py-0.5 ml-2 rounded-full bg-zinc-800 text-zinc-400 text-xs border border-zinc-700">DEV</span>
                    </div>
                    <div className="flex items-center gap-4 text-xs font-sans">
                        <div className="flex flex-col text-right">
                            <span className="text-zinc-500">Env: <span className="text-zinc-300">{process.env.NODE_ENV}</span></span>
                            <span className="text-zinc-500">Time: <span className="text-zinc-300">{new Date().toLocaleTimeString()}</span></span>
                        </div>
                        <button
                            onClick={() => { fetchNetworkData(); checkContracts(); }}
                            className="p-2 hover:bg-zinc-800 rounded-md transition-colors"
                            title="Refresh All"
                        >
                            <RefreshCw className="w-4 h-4 text-zinc-400" />
                        </button>
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">

                    {/* System & RPC Status */}
                    <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-5 space-y-4">
                        <div className="flex items-center gap-2 text-white font-semibold">
                            <Activity className="w-4 h-4 text-blue-400" />
                            <h3>System Status</h3>
                        </div>
                        <div className="space-y-3 pt-2">
                            <div className="flex justify-between items-center">
                                <span className="text-zinc-400">RPC Status</span>
                                <div className="flex items-center gap-2">
                                    <span className={rpcStatus === "CONNECTED" ? "text-emerald-400 font-bold" : "text-amber-500 font-bold"}>{rpcStatus}</span>
                                    <StatusIcon isGood={rpcStatus === "CONNECTED"} />
                                </div>
                            </div>
                            <div className="flex justify-between items-center">
                                <span className="text-zinc-400">Network</span>
                                <span>{networkInfo?.chain || "..."}</span>
                            </div>
                            <div className="flex justify-between items-center">
                                <span className="text-zinc-400">Latest Block</span>
                                <span className="text-blue-400">{networkInfo?.block || "..."}</span>
                            </div>
                            <div className="flex justify-between items-center">
                                <span className="text-zinc-400">Block Time</span>
                                <span>{networkInfo?.timestamp ? new Date(networkInfo.timestamp * 1000).toLocaleString() : "..."}</span>
                            </div>
                        </div>
                    </div>

                    {/* Environment Variables */}
                    <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-5 space-y-4 lg:col-span-2">
                        <div className="flex items-center gap-2 text-white font-semibold">
                            <Server className="w-4 h-4 text-purple-400" />
                            <h3>Environment Variables</h3>
                        </div>
                        <div className="grid grid-cols-1 gap-2 pt-2 text-xs">
                            {Object.entries(ENV_VARS).map(([key, val]) => (
                                <div key={key} className="flex flex-col sm:flex-row sm:justify-between py-1 border-b border-zinc-800/50">
                                    <span className="text-zinc-500">{key}</span>
                                    <span className={val ? "text-emerald-400 truncate max-w-xs" : "text-red-400"}>
                                        {val || "MISSING"}
                                    </span>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Contracts Status */}
                    <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-5 space-y-4 lg:col-span-3">
                        <div className="flex items-center gap-2 text-white font-semibold mb-2">
                            <FileCode className="w-4 h-4 text-emerald-400" />
                            <h3>Contracts State</h3>
                        </div>
                        <div className="overflow-x-auto">
                            <table className="w-full text-left text-xs whitespace-nowrap">
                                <thead>
                                    <tr className="text-zinc-500 border-b border-zinc-800">
                                        <th className="pb-2 font-medium">Contract</th>
                                        <th className="pb-2 font-medium">Address</th>
                                        <th className="pb-2 font-medium">Deployed</th>
                                        <th className="pb-2 font-medium">Class Hash</th>
                                        <th className="pb-2 font-medium px-2">Actions</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-zinc-800/50">
                                    {Object.entries(contractsStatus).map(([name, status]) => (
                                        <tr key={name} className="hover:bg-zinc-800/30 transition-colors">
                                            <td className="py-3 font-medium text-zinc-300">{name}</td>
                                            <td className="py-3 font-mono text-zinc-400">{status.address ? `${status.address.slice(0, 10)}...${status.address.slice(-8)}` : "MISSING"}</td>
                                            <td className="py-3">
                                                <div className="flex items-center gap-2">
                                                    <StatusIcon isGood={status.isDeployed} />
                                                    {status.isDeployed ? "YES" : status.isDeployed === false ? "NO" : "..."}
                                                </div>
                                            </td>
                                            <td className="py-3 font-mono text-zinc-500">{status.classHash ? `${status.classHash.slice(0, 10)}...` : "N/A"}</td>
                                            <td className="py-3 px-2">
                                                {name === "PolicyRegistry" && (
                                                    <button onClick={() => testContractCall("PolicyRegistry", status.address, "policy_commitment")} className="bg-zinc-800 hover:bg-zinc-700 text-zinc-300 px-2 py-1 rounded border border-zinc-700 flex items-center gap-1 transition-colors">
                                                        <Play className="w-3 h-3 text-blue-400" /> Call
                                                    </button>
                                                )}
                                                {name === "ProofVerifier" && (
                                                    <button onClick={() => testContractCall("ProofVerifier", status.address, "get_oracle_public_key")} className="bg-zinc-800 hover:bg-zinc-700 text-zinc-300 px-2 py-1 rounded border border-zinc-700 flex items-center gap-1 transition-colors">
                                                        <Play className="w-3 h-3 text-blue-400" /> Call
                                                    </button>
                                                )}
                                                {name === "GateAdapter" && (
                                                    <button onClick={() => testContractCall("GateAdapter", status.address, "owner")} className="bg-zinc-800 hover:bg-zinc-700 text-zinc-300 px-2 py-1 rounded border border-zinc-700 flex items-center gap-1 transition-colors">
                                                        <Play className="w-3 h-3 text-blue-400" /> Call
                                                    </button>
                                                )}
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>

                        {/* Show test results if any */}
                        {Object.keys(contractTests).length > 0 && (
                            <div className="mt-4 bg-zinc-950 p-3 rounded border border-zinc-800">
                                <h4 className="text-zinc-500 mb-2 text-xs uppercase font-bold tracking-wider">Test Results</h4>
                                {Object.entries(contractTests).map(([name, res]) => (
                                    <div key={name} className="text-xs space-y-1 mb-2 last:mb-0">
                                        <div className="text-zinc-300 font-medium">{name} test:</div>
                                        {res.loading && <div className="text-amber-500">Loading...</div>}
                                        {res.error && <div className="text-red-400 font-mono p-1 bg-red-950/20 rounded">Err: {res.error}</div>}
                                        {res.result && <div className="text-emerald-400 font-mono break-all bg-emerald-950/20 p-1 rounded">Res: {res.result}</div>}
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>

                    {/* Wallets */}
                    <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-5 space-y-4">
                        <div className="flex items-center gap-2 text-white font-semibold">
                            <Wallet className="w-4 h-4 text-pink-400" />
                            <h3>Wallet Connect</h3>
                        </div>
                        <div className="pt-2 space-y-3">
                            <div className="flexjustify-between items-center text-xs">
                                <span className="text-zinc-400">Status: </span>
                                <span className={accountStatus === "connected" ? "text-emerald-400" : "text-amber-500"}>{accountStatus}</span>
                            </div>

                            {accountStatus === "connected" ? (
                                <div className="space-y-2 text-xs">
                                    <div className="text-zinc-400">Address: <span className="text-blue-400 break-all">{address}</span></div>
                                    <div className="text-zinc-400">Connector: <span className="text-white">{connector?.name}</span></div>
                                    <button onClick={() => disconnect()} className="w-full mt-2 bg-red-900/40 hover:bg-red-900/60 text-red-200 py-1.5 rounded transition-colors border border-red-800/50">
                                        Disconnect
                                    </button>
                                </div>
                            ) : (
                                <div className="grid grid-cols-2 gap-2 text-xs">
                                    {connectors.map((c) => (
                                        <button
                                            key={c.id}
                                            onClick={() => connect({ connector: c })}
                                            disabled={!c.available()}
                                            className="bg-zinc-800 hover:bg-zinc-700 disabled:opacity-50 disabled:cursor-not-allowed text-zinc-300 py-2 rounded border border-zinc-700 flex flex-col items-center justify-center gap-1 transition-colors"
                                        >
                                            <img src={typeof c.icon === 'string' ? c.icon : c.icon.light} alt={c.name} className="w-5 h-5" />
                                            {c.name}
                                        </button>
                                    ))}
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Transaction Tests */}
                    <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-5 space-y-4 lg:col-span-2">
                        <div className="flex items-center gap-2 text-white font-semibold">
                            <Activity className="w-4 h-4 text-cyan-400" />
                            <h3>Transaction Test</h3>
                        </div>
                        <div className="space-y-3 pt-2">
                            <p className="text-xs text-zinc-400 leading-relaxed">
                                Test a full end-to-end Starknet transaction to verify proper function of the GateAdapter and connection.
                                Simulates `verify_and_register()` entrypoint on GateAdapter.
                            </p>

                            <button
                                onClick={executeVerifyAndRegister}
                                disabled={txTest.loading}
                                className="bg-cyan-900/40 hover:bg-cyan-900/60 text-cyan-200 px-4 py-2 border border-cyan-800/60 rounded text-xs font-semibold uppercase tracking-wider transition-colors disabled:opacity-50"
                            >
                                {txTest.loading ? "Executing..." : "Test Execute verify_and_register"}
                            </button>

                            {txTest.status && (
                                <div className="mt-2 p-3 bg-zinc-950 rounded border border-zinc-800 text-xs font-mono space-y-1">
                                    <div className="text-zinc-400">Status: <span className="text-white">{txTest.status}</span></div>
                                    {txTest.hash && <div className="text-blue-400 break-all">Hash: {txTest.hash}</div>}
                                    {txTest.error && <div className="text-red-400 break-all">Error: {txTest.error}</div>}
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Project Info */}
                    <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-5 space-y-4">
                        <div className="flex items-center gap-2 text-white font-semibold">
                            <Server className="w-4 h-4 text-indigo-400" />
                            <h3>Project Info</h3>
                        </div>
                        <div className="space-y-3 pt-2 text-xs">
                            <div className="flex justify-between items-center">
                                <span className="text-zinc-400">Environment</span>
                                <span className="text-zinc-300">{process.env.NODE_ENV}</span>
                            </div>
                            <div className="flex justify-between items-center">
                                <span className="text-zinc-400">Git Commit</span>
                                <span className="text-zinc-300 font-mono">{process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA?.slice(0, 7) || "Local"}</span>
                            </div>
                            <div className="flex justify-between items-center">
                                <span className="text-zinc-400">Deploy ID</span>
                                <span className="text-zinc-300 font-mono">{process.env.NEXT_PUBLIC_VERCEL_DEPLOYMENT_ID || "N/A"}</span>
                            </div>
                        </div>
                    </div>
                </div>

                {/* System Logs */}
                <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-5 space-y-4 h-96 flex flex-col">
                    <div className="flex items-center justify-between text-white font-semibold">
                        <div className="flex items-center gap-2">
                            <Terminal className="w-4 h-4 text-zinc-400" />
                            <h3>System Logs</h3>
                        </div>
                        {logs.length > 0 && (
                            <button onClick={() => setLogs([])} className="text-xs px-2 py-1 bg-zinc-800 hover:bg-zinc-700 rounded text-zinc-400 transition-colors">Clear</button>
                        )}
                    </div>
                    <div className="flex-1 overflow-y-auto font-mono text-xs p-3 bg-black rounded border border-zinc-800 space-y-1">
                        {logs.length === 0 ? (
                            <div className="text-zinc-600 italic">No logs intercepted yet...</div>
                        ) : (
                            logs.map((log, i) => (
                                <div key={i} className="flex gap-3 pt-1 border-t border-zinc-900/50 first:border-0 hover:bg-zinc-900/50">
                                    <span className="text-zinc-600 shrink-0">{log.timestamp}</span>
                                    <span className={`shrink-0 w-12 ${log.type === 'error' ? 'text-red-500' : log.type === 'warn' ? 'text-amber-500' : 'text-blue-500'}`}>[{log.type}]</span>
                                    <span className={`${log.type === 'error' ? 'text-red-300 break-all' : log.type === 'warn' ? 'text-amber-300' : 'text-zinc-300 break-all'}`}>
                                        {log.message}
                                    </span>
                                </div>
                            ))
                        )}
                    </div>
                </div>

            </div>
        </div>
    );
}
